# Generated by Django 2.2.6 on 2019-10-20 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='guardian_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
