# Generated by Django 2.2.6 on 2019-10-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191019_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='guardian_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
