# Generated by Django 2.2.6 on 2019-10-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191019_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bithday',
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patientsymptom',
            name='symptom',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
